### ISSUE TITLE
KP disagg for PrEP_NEW

### ISSUE THREAD

**Issue by mariaau2222** [USAID-OHA-SI/OHA-Tableau-Dashboard-QA-QC#39]
Q3 Data for KP disagg for PrEP_NEW not updated in Pano (still only have Q2 data)

**Comment by noahbartlett** [comment]
The Q3 data is included in the dashboards. Do you want me to remove it to be consistent with Pano?

**Comment by mariaau2222** [comment]
DATIM/Pano ticket issued.  DATIM Advanced Team is investigating.  Will keep you all posted.
