### ISSUE TITLE
KP Disagg for HTS

### ISSUE THREAD

**Issue by mariaau2222** [USAID-OHA-SI/OHA-Tableau-Dashboard-QA-QC#40]
Total #s tested among KP validated and are correct.  However, KP disagg for HTS POS not available in Pano's "Other/Additional Disaggs" Dashboard and cannot be verified.

**Comment by noahbartlett** [comment]
Do you want me to remove the Q3 data to be consistent with Pano? Or should we submit a ticket to ask Pano to update their data?

**Comment by mariaau2222** [comment]
We should probably ask Pano to update for both PrEP and HTS POS for KP.

**Comment by mariaau2222** [comment]
DATIM/Pano Ticket issued.  DATIM Advanced Team is investigating.
