### ISSUE TITLE
Executive Summary Format Review

### ISSUE THREAD

**Issue by kgichuhi** [USAID-OHA-SI/OHA-Tableau-Dashboard-QA-QC#49]
![image](https://user-images.githubusercontent.com/40864435/48954222-98ff7e80-ef16-11e8-8545-62bf69689871.png)

**Comment by jrose202** [comment]
USAID/other: edited
Agency contribution - alphabetical.  no re-ordering. talking points - send to Tim
Men: this workbook is created to populate a global slide deck.  if you go to tab 1 and choose a country you'll their specific figures. can't do top/bottom 5
Index testing: same as Men.  can't do top/bottom 5
EID coverage - calculated so there's not a target in the data set.  it would have to be created. trend lines not an option when comparing agencies this way.
VMMC -  if you go to tab 1 and choose a country you'll their specific figures
VMMC trends - tab deleted for country level visuals
Key pops - they're rather large circles - are you looking at the latest workbook?
FBO funding - this was designed to highlight FBO funding.  hence blue against grays
OVC tabs - all combine into another visual.  will edit/delete
