### ISSUE TITLE
FIRST PASS: OU.06: Age/Sex Results PMTCT, VMMC

### ISSUE THREAD

**Issue by gsarfaty** [USAID-OHA-SI/OHA-Tableau-Dashboard-QA-QC#53]
FIRST PASS issue - #50 

Inclusion of several extraneous standardized disaggs is causing double counting. 

Include only the following:

- HTS_SELF: Age/Sex/HIVSelfTest
- HTS_TST & TST_POS: Modality/Age/Sex/Result
- PMTCT_STAT, PMTCT_STAT_POS, PMTCT_ART: Age/Sex/KnownNew/Result
- TB_ART: Age/Sex/HIVStatus (pre-FY19), Age/Sex/NewExistingArt/HIVstatus (FY19)
- TB_STAT: AgeAggregated/Sex/KnownNewPosNeg (coarse pre-FY19); and Age/Sex/KnownNewPosNeg (FY19)
-TX_NEW, TX_CURR, TX_NET_NEW: Age/Sex/HIVStatus
-VMMC_CIRC: Age/Sex

**Comment by noahbartlett** [comment]
Fixed in the version I will upload later today. 

FYI, PMTCT_STAT has two age disags: Age/Sex and Age/Sex/KnownNew/Result, so I created a filter saying:
"Indicator= PMTCT_STAT and Standardized Disaggregate = Age/Sex"
and set it to false.
