### ISSUE TITLE
FIRST PASS: KP.00.Cascade table pulling incorrect values

### ISSUE THREAD

**Issue by gsarfaty** [USAID-OHA-SI/OHA-Tableau-Dashboard-QA-QC#54]
FIRST PASS #50

For the cascade table, need to add results or targets filter to get correct values

**Comment by noahbartlett** [comment]
Not able to replicate issue; please explain. Targets and results are the row values.

**Comment by gsarfaty** [comment]
Pesties chatted and this is resolved.
