### ISSUE TITLE
FIRST PASS - PMTCT.01 Positivity - Missing Age Disaggregation

### ISSUE THREAD

**Issue by nmcdavid** [USAID-OHA-SI/OHA-Tableau-Dashboard-QA-QC#55]
the table is missing the 10-14 age band and <10. Panorama is showing results for this age band

**Comment by noahbartlett** [comment]
I took out those age bands, since we don't tend to see a lot of pregnant women in those age bands. When we do, they tend to be data errors. 

I will put 10-14 back in if someone asks me nicely.
