### ISSUE TITLE
FIRST PASS - PMTCT.01 Positivity - FY18 results pullling from wrong standard disaggregate

### ISSUE THREAD

**Issue by nmcdavid** [USAID-OHA-SI/OHA-Tableau-Dashboard-QA-QC#56]
When checking pano using the age/sex dashboard, it looks like Panorama is using the Age/Sex disaggregate for the FY18 Results disaggregated by the Semi-fine age bands. 

When checking the fine age bands in Pano, it's unclear where the data is being pulled from.

**Comment by noahbartlett** [comment]
Agreed. The age disags for PMTCT_STAT have always been a bit wacky. Not sure I have a solution.

Think we have to strive for "consistent, not necessarily correct." SO we should make a call as to what "consistent" is.

**Comment by jrose202** [comment]
@nmcdavid  - can you weigh in on what to do?

**Comment by gsarfaty** [comment]
Doing final pass, agree the pano fine age bands for fy18 in the age/sex disagg dashboard are mysterious and match nothing comprehensible. My vote would be to leave ours (which I think is correct), and we can add the standardized disagg to the caption so people know where it's pulling. Ex below

![image](https://user-images.githubusercontent.com/11572993/53463599-52d62180-3a15-11e9-8812-ffe932ddfe24.png)

**Comment by jrose202** [comment]
looks good to me

**Comment by gsarfaty** [comment]
Then I hearby close this. @nmcdavid feel free to reopen if you feel otherwise.

**Comment by nmcdavid** [comment]
Thanks Gina. I'll leave it closed and will submit a pano ticket.

Nashiva
*NASHIVA McDAVID*
Program Analyst, SIEI/SI Team | Office of HIV/AIDS
U.S. AGENCY FOR INTERNATIONAL DEVELOPMENT
2100 Crystal Drive, #9062B, Arlington, VA 22202
(T) 571.551.7222 | (M) 202.679.9219 | nmcdavid@usaid.gov  |  USAID.gov  |
 @USAID
