### ISSUE TITLE
TX.08: VL Coverage Age/Sex

### ISSUE THREAD

**Issue by jaliasd** [USAID-OHA-SI/OHA-Tableau-Dashboard-QA-QC#64]
Folks, I'm not sure where to look on pano to QC this. The instructions say look at the “Treatment Continuum & Net New Visuals” Dashboard but when I do there isn't anything by age/sex see [here](https://drive.google.com/drive/folders/1ejIJkSd-2C6UALPA3WNBVoii_euY6So9)

I tried looking at the Viral Load (OU level) but that didn't have age/sex breakdowns other than at the PSNU level and that wasn't by agency (same link). So I don't know where to look to QC this.

**Comment by gsarfaty** [comment]
One option is to look at the age/sex disaggregates dashboard in Panorama, filtering indicators to just TX_CURR & TX_PVLS.

**Comment by jaliasd** [comment]
Ok Update, I did as @gsarfaty said and compared the TX_PVLS N and D values for two OUs against tableau. I had to hack the tableau dashboard to remove the sex filter to match Pano output. The values matched in both cases so I'm going to mark this done. I'm not sure where TX_CURR comes into play here. The % shown in the both dashboards are just TX_PVLS N/D. Thoughts?

**Comment by gsarfaty** [comment]
For tab **TX.08: VL Coverage Age/Sex** the % is calculating the proxy coverage as defined by TX_PVLS D/TX_CURR. 

The tooltip needs to be updated as it is only displaying the denominator of the calculation (TX_CURR) & is labeled as showing retention:
![image](https://user-images.githubusercontent.com/11572993/53425142-8469d100-39b2-11e9-8b1f-f745490d960d.png)

**Comment by jaliasd** [comment]
When I do the export excel from TX.08: VL Coverage Age/Sex, I only get the below

![image](https://user-images.githubusercontent.com/8836685/53428389-b8e08b80-39b8-11e9-805d-0c01d2caf35a.png)

When I look at the other tab 
![image](https://user-images.githubusercontent.com/8836685/53428500-e75e6680-39b8-11e9-9f53-7f4a6cd68bbf.png)

**Comment by jaliasd** [comment]
"Resolved" user error. Instructions need to be updated.

**Comment by noahbartlett** [comment]
Tooltip issue fixed.
