### ISSUE TITLE
no instructions TX.01: Cascade or TX.02: Peds Cascade

### ISSUE THREAD

**Issue by jaliasd** [USAID-OHA-SI/OHA-Tableau-Dashboard-QA-QC#66]
Two issues, the viz + tables in this one appear to be three separate objects so the export-excel option in the instructions doesn't work. Also, which is the relevent table in pano to check against? OU Level Results will give you tst, pos, and txnew, but where proxy retention is represented in pano

**Comment by jaliasd** [comment]
I can cross reference aspects of this tab to Pano, but I can't find proxy retention anywhere in Pano except one of the Dossiers and then it's by Age only, so I can't directly compare. For SA, it's "mostly" like what is in Pano so my suspicion is that the workbook is correct.

I checked the HTS_TST, HTS_TST_POS, TX_NEW, and Proxy Linkage for two OUs and they were correct. Please feel free to tic the box for this one if it satisfies you.

**Comment by gsarfaty** [comment]
Proxy retention = (TX_NET_NEW)/(TX_NEW). Can check num and den values for this via OU level results or TX continuum. I checked one OU and it was fine.
