### ISSUE TITLE
Second Pass OU Age/Sex Results

### ISSUE THREAD

**Issue by erinschelar** [USAID-OHA-SI/OHA-Tableau-Dashboard-QA-QC#72]
OU Age/Sex results tab passes QC except for coverage indicators where the numerator and denominator are being [summed together](https://drive.google.com/open?id=1IUxs-I3AipOBy5OhD_dN8NR_WY_UVocN). Values match Panorama, but this doesn't make sense from a data use perspective. 

@cnichols3h @nmcdavid for programmatic input

**Comment by noahbartlett** [comment]
This was an error. Should have only contained numerator. 

Fixed.
