### ISSUE TITLE
Suggestions to improve TB.01: Screen Neg tab

### ISSUE THREAD

**Issue by cnichols3h** [USAID-OHA-SI/OHA-Tableau-Dashboard-QA-QC#75]
The values are OK on this tab.  The following suggestions will make the visual clearer to the audience.
1. Suggestion to change title of TB.01 to "TB/HIV: ART patients screened negative for TB and TPT completion".
2. Suggestion to remove from the text box on the left: Percent of TB Cases who know their HIV status,  Percent of TB Cases who are HIV-positive who are on ART, and Percent of ART patients started on TB treatment.  The first two metrics other data points that are not represented on this page, so they might be confusing to the audience.  The last metric is not clinically or programmatically meaningful.
3. Suggestion to add the indicator names everywhere as it is not otherwise obvious to the audience what these are.  For ex., in the text box to the left, Percent of ART Patients screened for TB (=TX_TB / TX_CURR). For the bar graphs: ART patients (TX_CURR), ART patients screened for TB (TX_TB Den.), ART patients screened for TB: negative (TX_TB Den. NEG), ART patients expected to complete TPT (TB_PREV Den.), ART patients who completed TPT (TB_PREV Num.).
4. Suggestion to increase the font size of items 1-7 on the left side so that they are in-line w/ the data table to the right.

**Comment by gsarfaty** [comment]
1-3 are complete. 4 is a bit of a challenge in tableau unless we right align the text.
