### ISSUE TITLE
Suggestions to improve TB.02: Screen Pos tab

### ISSUE THREAD

**Issue by cnichols3h** [USAID-OHA-SI/OHA-Tableau-Dashboard-QA-QC#76]
The values are OK.  The following recommendations will make the data visuals clearer for the audience.
1. Suggestion to change title of TB.01 to "TB/HIV: ART patients screened positive for TB and TB treatment".
2. Suggestion to remove from the text box on the left: Percent of TB Cases who know their HIV status,  Percent of TB Cases who are HIV-positive who are on ART, and Percent of ART patients started on TB treatment.  The first two metrics other data points that are not represented on this page, so they might be confusing to the audience.  The last metric is not clinically or programmatically meaningful.
3. Suggestion to add the indicator names everywhere as it is not otherwise obvious to the audience what these are.  For ex., in the text box to the left, Percent of ART Patients screened for TB (=TX_TB / TX_CURR). For the bar graphs: ART patients (TX_CURR), ART patients screened for TB (TX_TB Den.), ART patients screened for TB: positive (TX_TB Den. POS), specimen sent for bacteriologic diagnosis (TX_TB Den. spec sent), ART patients with TB on TB treatment (TX_TB Num.).
4. Suggestion to increase the font size of items 1-5 on the left side so that they are in-line w/ the data table to the right.

**Comment by gsarfaty** [comment]
1-3 done. 4 would require r aligned text. holding off for now.
