### ISSUE TITLE
TX 08 - tooltip

### ISSUE THREAD

**Issue by jrose202** [USAID-OHA-SI/OHA-Tableau-Dashboard-QA-QC#78]
https://github.com/USAID-OHA-SI/OHA-Tableau-Dashboard-QA-QC/issues/50#issuecomment-467507041

Melaku said that the tooltip says "proxy treatment retention" - should be "proxy vl coverage".  value is VL but title says tx retention

**Comment by gsarfaty** [comment]
Cross with #64. Just fixed in working version I have open.
![image](https://user-images.githubusercontent.com/11572993/53461578-04258900-3a0f-11e9-9ded-8d18e777a58f.png)
